---
name: Push to wiki

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

  # Manually triggered from the GitHub Actions UI.
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Push to wiki repo
      run: |
        git config user.name "GitHub Actions on behalf of $(jq -r '.pusher.name' "$GITHUB_EVENT_PATH")"
        git config user.email "$GITHUB_ACTION@actions.noreply.github.com"

        git remote add wiki https://${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.wiki.git
        git fetch wiki
        git checkout -b wiki-master wiki/master
        git merge --ff --no-edit origin/master
        git push wiki wiki-master:master
